// Dart parity source: flutter/packages/flutter/lib/src/services/keyboard_key.g.dart
//
// The 444 logical and 269 physical key constants and their lookup tables are generated into
// KeyboardKey.g.cs by scripts/generate_keyboard_keys.py, mirroring how Flutter generates
// keyboard_key.g.dart itself. This file holds the hand-written class bodies.

using System.Globalization;
using Plumix.Foundation;

namespace Plumix.UI;

/// <summary>A base class for all keyboard key types.</summary>
public abstract class KeyboardKey
{
    protected KeyboardKey()
    {
    }

    public virtual void DebugFillProperties(DiagnosticPropertiesBuilder properties)
    {
        ArgumentNullException.ThrowIfNull(properties);
    }
}

/// <summary>
/// A class with static values that describe the keys that are returned from
/// <see cref="KeyEvent.LogicalKey"/> — keys interpreted in the context of any modifiers, modes,
/// or keyboard layouts which may be in effect.
/// </summary>
public sealed partial class LogicalKeyboardKey : KeyboardKey, IEquatable<LogicalKeyboardKey>
{
    public LogicalKeyboardKey(long keyId)
    {
        KeyId = keyId;
    }

    public long KeyId { get; }

    /// <summary>The Unicode string representing the character produced by a key event.</summary>
    public string KeyLabel => UnicodeKeyLabel(KeyId) ?? (KeyLabelsById.GetValueOrDefault(KeyId) ?? string.Empty);

    /// <summary>The debug string to print for this key, intended for debugging only.</summary>
    public string DebugName
    {
        get
        {
            if (KeyLabelsById.TryGetValue(KeyId, out string? label))
            {
                return label;
            }

            string? unicodeKeyLabel = UnicodeKeyLabel(KeyId);
            return unicodeKeyLabel != null
                ? $"Key {unicodeKeyLabel}"
                : $"Key with ID 0x{KeyId.ToString("x11", CultureInfo.InvariantCulture)}";
        }
    }

    /// <summary>
    /// Whether this key is autogenerated, i.e. synthesized by the framework for a platform key
    /// with no known logical key mapping.
    /// </summary>
    public bool IsAutogenerated => (KeyId & PlaneMask) >= StartOfPlatformPlanes;

    /// <summary>The set of pseudo-keys this key is a synonym for (for example `Shift` for `ShiftLeft`).</summary>
    public IReadOnlySet<LogicalKeyboardKey> Synonyms =>
        SynonymTables.Synonyms.GetValueOrDefault(this) ?? new HashSet<LogicalKeyboardKey>();

    public static LogicalKeyboardKey? FindKeyByKeyId(long keyId) => KnownLogicalKeysById.GetValueOrDefault(keyId);

    /// <summary>All the keys known to the framework, keyed by their <see cref="KeyId"/>.</summary>
    public static IEnumerable<LogicalKeyboardKey> KnownLogicalKeys => KnownLogicalKeysById.Values;

    /// <summary>Whether the given label represents an unprintable key.</summary>
    public static bool IsControlCharacter(string label)
    {
        ArgumentNullException.ThrowIfNull(label);
        if (label.Length != 1)
        {
            return false;
        }

        int codeUnit = label[0];
        return codeUnit is (>= 0x00 and <= 0x1f) or (>= 0x7f and <= 0x9f);
    }

    /// <summary>Returns a set of pseudo-key synonyms for the given <paramref name="input"/> keys.</summary>
    public static IReadOnlySet<LogicalKeyboardKey> CollapseSynonyms(IReadOnlySet<LogicalKeyboardKey> input)
    {
        ArgumentNullException.ThrowIfNull(input);
        var result = new HashSet<LogicalKeyboardKey>();
        foreach (LogicalKeyboardKey element in input)
        {
            if (SynonymTables.Synonyms.TryGetValue(element, out IReadOnlySet<LogicalKeyboardKey>? synonyms))
            {
                result.UnionWith(synonyms);
            }
            else
            {
                result.Add(element);
            }
        }

        return result;
    }

    /// <summary>Returns the given set with each pseudo-key replaced by the keys it stands for.</summary>
    public static IReadOnlySet<LogicalKeyboardKey> ExpandSynonyms(IReadOnlySet<LogicalKeyboardKey> input)
    {
        ArgumentNullException.ThrowIfNull(input);
        var result = new HashSet<LogicalKeyboardKey>();
        foreach (LogicalKeyboardKey element in input)
        {
            if (SynonymTables.ReverseSynonyms.TryGetValue(element, out IReadOnlySet<LogicalKeyboardKey>? expanded))
            {
                result.UnionWith(expanded);
            }
            else
            {
                result.Add(element);
            }
        }

        return result;
    }

    public bool Equals(LogicalKeyboardKey? other) => other != null && other.KeyId == KeyId;

    public override bool Equals(object? obj) => obj is LogicalKeyboardKey other && Equals(other);

    public override int GetHashCode() => KeyId.GetHashCode();

    public override void DebugFillProperties(DiagnosticPropertiesBuilder properties)
    {
        base.DebugFillProperties(properties);
        properties.Add(new StringProperty("keyId", $"0x{KeyId.ToString("x8", CultureInfo.InvariantCulture)}"));
        properties.Add(new StringProperty("keyLabel", KeyLabel));
        properties.Add(new StringProperty("debugName", DebugName));
    }

    public override string ToString() => DebugName;

    /// <summary>Mask for the 32-bit value portion of the key code.</summary>
    public const long ValueMask = 0x000ffffffff;

    /// <summary>Mask for the plane prefix portion of the key code.</summary>
    public const long PlaneMask = 0x0ff00000000;

    /// <summary>The plane value for keys which have a Unicode representation.</summary>
    public const long UnicodePlane = 0x00000000000;

    /// <summary>The plane value for keys defined by Chromium and does not have a Unicode representation.</summary>
    public const long UnprintablePlane = 0x00100000000;

    /// <summary>The plane value for keys defined by Flutter.</summary>
    public const long FlutterPlane = 0x00200000000;

    /// <summary>The platform plane with the lowest mask value.</summary>
    public const long StartOfPlatformPlanes = 0x01100000000;

    /// <summary>The plane value for the private keys defined by the Android embedding.</summary>
    public const long AndroidPlane = 0x01100000000;

    /// <summary>The plane value for the private keys defined by the Fuchsia embedding.</summary>
    public const long FuchsiaPlane = 0x01200000000;

    /// <summary>The plane value for the private keys defined by the iOS embedding.</summary>
    public const long IosPlane = 0x01300000000;

    /// <summary>The plane value for the private keys defined by the macOS embedding.</summary>
    public const long MacosPlane = 0x01400000000;

    /// <summary>The plane value for the private keys defined by the GTK embedding.</summary>
    public const long GtkPlane = 0x01500000000;

    /// <summary>The plane value for the private keys defined by the Windows embedding.</summary>
    public const long WindowsPlane = 0x01600000000;

    /// <summary>The plane value for the private keys defined by the Web embedding.</summary>
    public const long WebPlane = 0x01700000000;

    /// <summary>The plane value for the private keys defined by the GLFW embedding.</summary>
    public const long GlfwPlane = 0x01800000000;

    // Returns the bits that are not included in [ValueMask], shifted to the right.
    private static long NonValueBits(long n)
    {
        const int valueMaskWidth = 32;
        const int maxSafeIntegerWidth = 52;
        const long nonValueMask = (1L << (maxSafeIntegerWidth - valueMaskWidth)) - 1;
        return (n >> valueMaskWidth) & nonValueMask;
    }

    private static string? UnicodeKeyLabel(long keyId)
    {
        if (NonValueBits(keyId) == 0)
        {
            return char.ConvertFromUtf32((int)keyId).ToUpperInvariant();
        }

        return null;
    }

    // Static initialization order across partial-class parts is unspecified, so the synonym maps —
    // which reference the generated constants — live in a nested holder that initializes on demand.
    private static class SynonymTables
    {
        public static readonly Dictionary<LogicalKeyboardKey, IReadOnlySet<LogicalKeyboardKey>> Synonyms = new()
        {
            [ShiftLeft] = new HashSet<LogicalKeyboardKey> { Shift },
            [ShiftRight] = new HashSet<LogicalKeyboardKey> { Shift },
            [MetaLeft] = new HashSet<LogicalKeyboardKey> { Meta },
            [MetaRight] = new HashSet<LogicalKeyboardKey> { Meta },
            [AltLeft] = new HashSet<LogicalKeyboardKey> { Alt },
            [AltRight] = new HashSet<LogicalKeyboardKey> { Alt },
            [ControlLeft] = new HashSet<LogicalKeyboardKey> { Control },
            [ControlRight] = new HashSet<LogicalKeyboardKey> { Control },
        };

        public static readonly Dictionary<LogicalKeyboardKey, IReadOnlySet<LogicalKeyboardKey>> ReverseSynonyms =
            new()
            {
                [Shift] = new HashSet<LogicalKeyboardKey> { ShiftLeft, ShiftRight },
                [Meta] = new HashSet<LogicalKeyboardKey> { MetaLeft, MetaRight },
                [Alt] = new HashSet<LogicalKeyboardKey> { AltLeft, AltRight },
                [Control] = new HashSet<LogicalKeyboardKey> { ControlLeft, ControlRight },
            };
    }
}

/// <summary>
/// A class with static values that describe the keys that are returned from
/// <see cref="KeyEvent.PhysicalKey"/> — the physical location of a key on the keyboard,
/// independent of modifiers, modes, or keyboard layout.
/// </summary>
public sealed partial class PhysicalKeyboardKey : KeyboardKey, IEquatable<PhysicalKeyboardKey>
{
    public PhysicalKeyboardKey(long usbHidUsage)
    {
        UsbHidUsage = usbHidUsage;
    }

    /// <summary>The unique USB HID usage ID of this physical key on the keyboard.</summary>
    public long UsbHidUsage { get; }

    /// <summary>The debug string to print for this key, intended for debugging only.</summary>
    public string DebugName => DebugNamesByCode.GetValueOrDefault(UsbHidUsage)
                               ?? $"Key with ID 0x{UsbHidUsage.ToString("x8", CultureInfo.InvariantCulture)}";

    public static PhysicalKeyboardKey? FindKeyByCode(long usageCode) =>
        KnownPhysicalKeysByCode.GetValueOrDefault(usageCode);

    /// <summary>All the physical keys known to the framework.</summary>
    public static IEnumerable<PhysicalKeyboardKey> KnownPhysicalKeys => KnownPhysicalKeysByCode.Values;

    public bool Equals(PhysicalKeyboardKey? other) => other != null && other.UsbHidUsage == UsbHidUsage;

    public override bool Equals(object? obj) => obj is PhysicalKeyboardKey other && Equals(other);

    public override int GetHashCode() => UsbHidUsage.GetHashCode();

    public override void DebugFillProperties(DiagnosticPropertiesBuilder properties)
    {
        base.DebugFillProperties(properties);
        properties.Add(new StringProperty(
            "usbHidUsage",
            $"0x{UsbHidUsage.ToString("x8", CultureInfo.InvariantCulture)}"));
        properties.Add(new StringProperty("debugName", DebugName));
    }

    public override string ToString() => DebugName;
}
