// Dart parity source: material_ui/lib/src/colors.dart
//
// DO NOT EDIT -- DO NOT EDIT -- DO NOT EDIT
// Generated by scripts/generate_material_colors.py from the material_ui package's colors.dart.
// Regenerate after moving the material_ui pin; edit the script, not this file.

namespace Plumix.Material;

/// <summary>
/// <see cref="Color"/> and <see cref="ColorSwatch{T}"/> constants that represent Material Design's
/// color palette.
/// </summary>
public static class Colors
{
    /// <summary>Completely invisible.</summary>
    public static readonly Color Transparent = new Color(0x00000000);

    /// <summary>Completely opaque black.</summary>
    public static readonly Color Black = new Color(0xFF000000);

    /// <summary>Black with 87% opacity.</summary>
    public static readonly Color Black87 = new Color(0xDD000000);

    /// <summary>Black with 54% opacity.</summary>
    public static readonly Color Black54 = new Color(0x8A000000);

    /// <summary>Black with 45% opacity.</summary>
    public static readonly Color Black45 = new Color(0x73000000);

    /// <summary>Black with 38% opacity.</summary>
    public static readonly Color Black38 = new Color(0x61000000);

    /// <summary>Black with 26% opacity.</summary>
    public static readonly Color Black26 = new Color(0x42000000);

    /// <summary>Black with 12% opacity.</summary>
    public static readonly Color Black12 = new Color(0x1F000000);

    /// <summary>Completely opaque white.</summary>
    public static readonly Color White = new Color(0xFFFFFFFF);

    /// <summary>White with 70% opacity.</summary>
    public static readonly Color White70 = new Color(0xB3FFFFFF);

    /// <summary>White with 60% opacity.</summary>
    public static readonly Color White60 = new Color(0x99FFFFFF);

    /// <summary>White with 54% opacity.</summary>
    public static readonly Color White54 = new Color(0x8AFFFFFF);

    /// <summary>White with 38% opacity.</summary>
    public static readonly Color White38 = new Color(0x62FFFFFF);

    /// <summary>White with 30% opacity.</summary>
    public static readonly Color White30 = new Color(0x4DFFFFFF);

    /// <summary>White with 24% opacity.</summary>
    public static readonly Color White24 = new Color(0x3DFFFFFF);

    /// <summary>White with 12% opacity.</summary>
    public static readonly Color White12 = new Color(0x1FFFFFFF);

    /// <summary>White with 10% opacity.</summary>
    public static readonly Color White10 = new Color(0x1AFFFFFF);

    /// <summary>The red primary swatch.</summary>
    public static readonly MaterialColor Red = new(
        0xFFF44336,
        new Dictionary<int, Color>
        {
            [50] = new Color(0xFFFFEBEE),
            [100] = new Color(0xFFFFCDD2),
            [200] = new Color(0xFFEF9A9A),
            [300] = new Color(0xFFE57373),
            [400] = new Color(0xFFEF5350),
            [500] = new Color(0xFFF44336),
            [600] = new Color(0xFFE53935),
            [700] = new Color(0xFFD32F2F),
            [800] = new Color(0xFFC62828),
            [900] = new Color(0xFFB71C1C),
        });

    /// <summary>The redAccent accent swatch.</summary>
    public static readonly MaterialAccentColor RedAccent = new(
        0xFFFF5252,
        new Dictionary<int, Color>
        {
            [100] = new Color(0xFFFF8A80),
            [200] = new Color(0xFFFF5252),
            [400] = new Color(0xFFFF1744),
            [700] = new Color(0xFFD50000),
        });

    /// <summary>The pink primary swatch.</summary>
    public static readonly MaterialColor Pink = new(
        0xFFE91E63,
        new Dictionary<int, Color>
        {
            [50] = new Color(0xFFFCE4EC),
            [100] = new Color(0xFFF8BBD0),
            [200] = new Color(0xFFF48FB1),
            [300] = new Color(0xFFF06292),
            [400] = new Color(0xFFEC407A),
            [500] = new Color(0xFFE91E63),
            [600] = new Color(0xFFD81B60),
            [700] = new Color(0xFFC2185B),
            [800] = new Color(0xFFAD1457),
            [900] = new Color(0xFF880E4F),
        });

    /// <summary>The pinkAccent accent swatch.</summary>
    public static readonly MaterialAccentColor PinkAccent = new(
        0xFFFF4081,
        new Dictionary<int, Color>
        {
            [100] = new Color(0xFFFF80AB),
            [200] = new Color(0xFFFF4081),
            [400] = new Color(0xFFF50057),
            [700] = new Color(0xFFC51162),
        });

    /// <summary>The purple primary swatch.</summary>
    public static readonly MaterialColor Purple = new(
        0xFF9C27B0,
        new Dictionary<int, Color>
        {
            [50] = new Color(0xFFF3E5F5),
            [100] = new Color(0xFFE1BEE7),
            [200] = new Color(0xFFCE93D8),
            [300] = new Color(0xFFBA68C8),
            [400] = new Color(0xFFAB47BC),
            [500] = new Color(0xFF9C27B0),
            [600] = new Color(0xFF8E24AA),
            [700] = new Color(0xFF7B1FA2),
            [800] = new Color(0xFF6A1B9A),
            [900] = new Color(0xFF4A148C),
        });

    /// <summary>The purpleAccent accent swatch.</summary>
    public static readonly MaterialAccentColor PurpleAccent = new(
        0xFFE040FB,
        new Dictionary<int, Color>
        {
            [100] = new Color(0xFFEA80FC),
            [200] = new Color(0xFFE040FB),
            [400] = new Color(0xFFD500F9),
            [700] = new Color(0xFFAA00FF),
        });

    /// <summary>The deepPurple primary swatch.</summary>
    public static readonly MaterialColor DeepPurple = new(
        0xFF673AB7,
        new Dictionary<int, Color>
        {
            [50] = new Color(0xFFEDE7F6),
            [100] = new Color(0xFFD1C4E9),
            [200] = new Color(0xFFB39DDB),
            [300] = new Color(0xFF9575CD),
            [400] = new Color(0xFF7E57C2),
            [500] = new Color(0xFF673AB7),
            [600] = new Color(0xFF5E35B1),
            [700] = new Color(0xFF512DA8),
            [800] = new Color(0xFF4527A0),
            [900] = new Color(0xFF311B92),
        });

    /// <summary>The deepPurpleAccent accent swatch.</summary>
    public static readonly MaterialAccentColor DeepPurpleAccent = new(
        0xFF7C4DFF,
        new Dictionary<int, Color>
        {
            [100] = new Color(0xFFB388FF),
            [200] = new Color(0xFF7C4DFF),
            [400] = new Color(0xFF651FFF),
            [700] = new Color(0xFF6200EA),
        });

    /// <summary>The indigo primary swatch.</summary>
    public static readonly MaterialColor Indigo = new(
        0xFF3F51B5,
        new Dictionary<int, Color>
        {
            [50] = new Color(0xFFE8EAF6),
            [100] = new Color(0xFFC5CAE9),
            [200] = new Color(0xFF9FA8DA),
            [300] = new Color(0xFF7986CB),
            [400] = new Color(0xFF5C6BC0),
            [500] = new Color(0xFF3F51B5),
            [600] = new Color(0xFF3949AB),
            [700] = new Color(0xFF303F9F),
            [800] = new Color(0xFF283593),
            [900] = new Color(0xFF1A237E),
        });

    /// <summary>The indigoAccent accent swatch.</summary>
    public static readonly MaterialAccentColor IndigoAccent = new(
        0xFF536DFE,
        new Dictionary<int, Color>
        {
            [100] = new Color(0xFF8C9EFF),
            [200] = new Color(0xFF536DFE),
            [400] = new Color(0xFF3D5AFE),
            [700] = new Color(0xFF304FFE),
        });

    /// <summary>The blue primary swatch.</summary>
    public static readonly MaterialColor Blue = new(
        0xFF2196F3,
        new Dictionary<int, Color>
        {
            [50] = new Color(0xFFE3F2FD),
            [100] = new Color(0xFFBBDEFB),
            [200] = new Color(0xFF90CAF9),
            [300] = new Color(0xFF64B5F6),
            [400] = new Color(0xFF42A5F5),
            [500] = new Color(0xFF2196F3),
            [600] = new Color(0xFF1E88E5),
            [700] = new Color(0xFF1976D2),
            [800] = new Color(0xFF1565C0),
            [900] = new Color(0xFF0D47A1),
        });

    /// <summary>The blueAccent accent swatch.</summary>
    public static readonly MaterialAccentColor BlueAccent = new(
        0xFF448AFF,
        new Dictionary<int, Color>
        {
            [100] = new Color(0xFF82B1FF),
            [200] = new Color(0xFF448AFF),
            [400] = new Color(0xFF2979FF),
            [700] = new Color(0xFF2962FF),
        });

    /// <summary>The lightBlue primary swatch.</summary>
    public static readonly MaterialColor LightBlue = new(
        0xFF03A9F4,
        new Dictionary<int, Color>
        {
            [50] = new Color(0xFFE1F5FE),
            [100] = new Color(0xFFB3E5FC),
            [200] = new Color(0xFF81D4FA),
            [300] = new Color(0xFF4FC3F7),
            [400] = new Color(0xFF29B6F6),
            [500] = new Color(0xFF03A9F4),
            [600] = new Color(0xFF039BE5),
            [700] = new Color(0xFF0288D1),
            [800] = new Color(0xFF0277BD),
            [900] = new Color(0xFF01579B),
        });

    /// <summary>The lightBlueAccent accent swatch.</summary>
    public static readonly MaterialAccentColor LightBlueAccent = new(
        0xFF40C4FF,
        new Dictionary<int, Color>
        {
            [100] = new Color(0xFF80D8FF),
            [200] = new Color(0xFF40C4FF),
            [400] = new Color(0xFF00B0FF),
            [700] = new Color(0xFF0091EA),
        });

    /// <summary>The cyan primary swatch.</summary>
    public static readonly MaterialColor Cyan = new(
        0xFF00BCD4,
        new Dictionary<int, Color>
        {
            [50] = new Color(0xFFE0F7FA),
            [100] = new Color(0xFFB2EBF2),
            [200] = new Color(0xFF80DEEA),
            [300] = new Color(0xFF4DD0E1),
            [400] = new Color(0xFF26C6DA),
            [500] = new Color(0xFF00BCD4),
            [600] = new Color(0xFF00ACC1),
            [700] = new Color(0xFF0097A7),
            [800] = new Color(0xFF00838F),
            [900] = new Color(0xFF006064),
        });

    /// <summary>The cyanAccent accent swatch.</summary>
    public static readonly MaterialAccentColor CyanAccent = new(
        0xFF18FFFF,
        new Dictionary<int, Color>
        {
            [100] = new Color(0xFF84FFFF),
            [200] = new Color(0xFF18FFFF),
            [400] = new Color(0xFF00E5FF),
            [700] = new Color(0xFF00B8D4),
        });

    /// <summary>The teal primary swatch.</summary>
    public static readonly MaterialColor Teal = new(
        0xFF009688,
        new Dictionary<int, Color>
        {
            [50] = new Color(0xFFE0F2F1),
            [100] = new Color(0xFFB2DFDB),
            [200] = new Color(0xFF80CBC4),
            [300] = new Color(0xFF4DB6AC),
            [400] = new Color(0xFF26A69A),
            [500] = new Color(0xFF009688),
            [600] = new Color(0xFF00897B),
            [700] = new Color(0xFF00796B),
            [800] = new Color(0xFF00695C),
            [900] = new Color(0xFF004D40),
        });

    /// <summary>The tealAccent accent swatch.</summary>
    public static readonly MaterialAccentColor TealAccent = new(
        0xFF64FFDA,
        new Dictionary<int, Color>
        {
            [100] = new Color(0xFFA7FFEB),
            [200] = new Color(0xFF64FFDA),
            [400] = new Color(0xFF1DE9B6),
            [700] = new Color(0xFF00BFA5),
        });

    /// <summary>The green primary swatch.</summary>
    public static readonly MaterialColor Green = new(
        0xFF4CAF50,
        new Dictionary<int, Color>
        {
            [50] = new Color(0xFFE8F5E9),
            [100] = new Color(0xFFC8E6C9),
            [200] = new Color(0xFFA5D6A7),
            [300] = new Color(0xFF81C784),
            [400] = new Color(0xFF66BB6A),
            [500] = new Color(0xFF4CAF50),
            [600] = new Color(0xFF43A047),
            [700] = new Color(0xFF388E3C),
            [800] = new Color(0xFF2E7D32),
            [900] = new Color(0xFF1B5E20),
        });

    /// <summary>The greenAccent accent swatch.</summary>
    public static readonly MaterialAccentColor GreenAccent = new(
        0xFF69F0AE,
        new Dictionary<int, Color>
        {
            [100] = new Color(0xFFB9F6CA),
            [200] = new Color(0xFF69F0AE),
            [400] = new Color(0xFF00E676),
            [700] = new Color(0xFF00C853),
        });

    /// <summary>The lightGreen primary swatch.</summary>
    public static readonly MaterialColor LightGreen = new(
        0xFF8BC34A,
        new Dictionary<int, Color>
        {
            [50] = new Color(0xFFF1F8E9),
            [100] = new Color(0xFFDCEDC8),
            [200] = new Color(0xFFC5E1A5),
            [300] = new Color(0xFFAED581),
            [400] = new Color(0xFF9CCC65),
            [500] = new Color(0xFF8BC34A),
            [600] = new Color(0xFF7CB342),
            [700] = new Color(0xFF689F38),
            [800] = new Color(0xFF558B2F),
            [900] = new Color(0xFF33691E),
        });

    /// <summary>The lightGreenAccent accent swatch.</summary>
    public static readonly MaterialAccentColor LightGreenAccent = new(
        0xFFB2FF59,
        new Dictionary<int, Color>
        {
            [100] = new Color(0xFFCCFF90),
            [200] = new Color(0xFFB2FF59),
            [400] = new Color(0xFF76FF03),
            [700] = new Color(0xFF64DD17),
        });

    /// <summary>The lime primary swatch.</summary>
    public static readonly MaterialColor Lime = new(
        0xFFCDDC39,
        new Dictionary<int, Color>
        {
            [50] = new Color(0xFFF9FBE7),
            [100] = new Color(0xFFF0F4C3),
            [200] = new Color(0xFFE6EE9C),
            [300] = new Color(0xFFDCE775),
            [400] = new Color(0xFFD4E157),
            [500] = new Color(0xFFCDDC39),
            [600] = new Color(0xFFC0CA33),
            [700] = new Color(0xFFAFB42B),
            [800] = new Color(0xFF9E9D24),
            [900] = new Color(0xFF827717),
        });

    /// <summary>The limeAccent accent swatch.</summary>
    public static readonly MaterialAccentColor LimeAccent = new(
        0xFFEEFF41,
        new Dictionary<int, Color>
        {
            [100] = new Color(0xFFF4FF81),
            [200] = new Color(0xFFEEFF41),
            [400] = new Color(0xFFC6FF00),
            [700] = new Color(0xFFAEEA00),
        });

    /// <summary>The yellow primary swatch.</summary>
    public static readonly MaterialColor Yellow = new(
        0xFFFFEB3B,
        new Dictionary<int, Color>
        {
            [50] = new Color(0xFFFFFDE7),
            [100] = new Color(0xFFFFF9C4),
            [200] = new Color(0xFFFFF59D),
            [300] = new Color(0xFFFFF176),
            [400] = new Color(0xFFFFEE58),
            [500] = new Color(0xFFFFEB3B),
            [600] = new Color(0xFFFDD835),
            [700] = new Color(0xFFFBC02D),
            [800] = new Color(0xFFF9A825),
            [900] = new Color(0xFFF57F17),
        });

    /// <summary>The yellowAccent accent swatch.</summary>
    public static readonly MaterialAccentColor YellowAccent = new(
        0xFFFFFF00,
        new Dictionary<int, Color>
        {
            [100] = new Color(0xFFFFFF8D),
            [200] = new Color(0xFFFFFF00),
            [400] = new Color(0xFFFFEA00),
            [700] = new Color(0xFFFFD600),
        });

    /// <summary>The amber primary swatch.</summary>
    public static readonly MaterialColor Amber = new(
        0xFFFFC107,
        new Dictionary<int, Color>
        {
            [50] = new Color(0xFFFFF8E1),
            [100] = new Color(0xFFFFECB3),
            [200] = new Color(0xFFFFE082),
            [300] = new Color(0xFFFFD54F),
            [400] = new Color(0xFFFFCA28),
            [500] = new Color(0xFFFFC107),
            [600] = new Color(0xFFFFB300),
            [700] = new Color(0xFFFFA000),
            [800] = new Color(0xFFFF8F00),
            [900] = new Color(0xFFFF6F00),
        });

    /// <summary>The amberAccent accent swatch.</summary>
    public static readonly MaterialAccentColor AmberAccent = new(
        0xFFFFD740,
        new Dictionary<int, Color>
        {
            [100] = new Color(0xFFFFE57F),
            [200] = new Color(0xFFFFD740),
            [400] = new Color(0xFFFFC400),
            [700] = new Color(0xFFFFAB00),
        });

    /// <summary>The orange primary swatch.</summary>
    public static readonly MaterialColor Orange = new(
        0xFFFF9800,
        new Dictionary<int, Color>
        {
            [50] = new Color(0xFFFFF3E0),
            [100] = new Color(0xFFFFE0B2),
            [200] = new Color(0xFFFFCC80),
            [300] = new Color(0xFFFFB74D),
            [400] = new Color(0xFFFFA726),
            [500] = new Color(0xFFFF9800),
            [600] = new Color(0xFFFB8C00),
            [700] = new Color(0xFFF57C00),
            [800] = new Color(0xFFEF6C00),
            [900] = new Color(0xFFE65100),
        });

    /// <summary>The orangeAccent accent swatch.</summary>
    public static readonly MaterialAccentColor OrangeAccent = new(
        0xFFFFAB40,
        new Dictionary<int, Color>
        {
            [100] = new Color(0xFFFFD180),
            [200] = new Color(0xFFFFAB40),
            [400] = new Color(0xFFFF9100),
            [700] = new Color(0xFFFF6D00),
        });

    /// <summary>The deepOrange primary swatch.</summary>
    public static readonly MaterialColor DeepOrange = new(
        0xFFFF5722,
        new Dictionary<int, Color>
        {
            [50] = new Color(0xFFFBE9E7),
            [100] = new Color(0xFFFFCCBC),
            [200] = new Color(0xFFFFAB91),
            [300] = new Color(0xFFFF8A65),
            [400] = new Color(0xFFFF7043),
            [500] = new Color(0xFFFF5722),
            [600] = new Color(0xFFF4511E),
            [700] = new Color(0xFFE64A19),
            [800] = new Color(0xFFD84315),
            [900] = new Color(0xFFBF360C),
        });

    /// <summary>The deepOrangeAccent accent swatch.</summary>
    public static readonly MaterialAccentColor DeepOrangeAccent = new(
        0xFFFF6E40,
        new Dictionary<int, Color>
        {
            [100] = new Color(0xFFFF9E80),
            [200] = new Color(0xFFFF6E40),
            [400] = new Color(0xFFFF3D00),
            [700] = new Color(0xFFDD2C00),
        });

    /// <summary>The brown primary swatch.</summary>
    public static readonly MaterialColor Brown = new(
        0xFF795548,
        new Dictionary<int, Color>
        {
            [50] = new Color(0xFFEFEBE9),
            [100] = new Color(0xFFD7CCC8),
            [200] = new Color(0xFFBCAAA4),
            [300] = new Color(0xFFA1887F),
            [400] = new Color(0xFF8D6E63),
            [500] = new Color(0xFF795548),
            [600] = new Color(0xFF6D4C41),
            [700] = new Color(0xFF5D4037),
            [800] = new Color(0xFF4E342E),
            [900] = new Color(0xFF3E2723),
        });

    /// <summary>The grey primary swatch.</summary>
    public static readonly MaterialColor Grey = new(
        0xFF9E9E9E,
        new Dictionary<int, Color>
        {
            [50] = new Color(0xFFFAFAFA),
            [100] = new Color(0xFFF5F5F5),
            [200] = new Color(0xFFEEEEEE),
            [300] = new Color(0xFFE0E0E0),
            [350] = new Color(0xFFD6D6D6), // only for raised button while pressed in light theme
            [400] = new Color(0xFFBDBDBD),
            [500] = new Color(0xFF9E9E9E),
            [600] = new Color(0xFF757575),
            [700] = new Color(0xFF616161),
            [800] = new Color(0xFF424242),
            [850] = new Color(0xFF303030), // only for background color in dark theme
            [900] = new Color(0xFF212121),
        });

    /// <summary>The blueGrey primary swatch.</summary>
    public static readonly MaterialColor BlueGrey = new(
        0xFF607D8B,
        new Dictionary<int, Color>
        {
            [50] = new Color(0xFFECEFF1),
            [100] = new Color(0xFFCFD8DC),
            [200] = new Color(0xFFB0BEC5),
            [300] = new Color(0xFF90A4AE),
            [400] = new Color(0xFF78909C),
            [500] = new Color(0xFF607D8B),
            [600] = new Color(0xFF546E7A),
            [700] = new Color(0xFF455A64),
            [800] = new Color(0xFF37474F),
            [900] = new Color(0xFF263238),
        });

    /// <summary>The Material Design primary color swatches, excluding grey.</summary>
    public static readonly IReadOnlyList<MaterialColor> Primaries =
    [
        Red,
        Pink,
        Purple,
        DeepPurple,
        Indigo,
        Blue,
        LightBlue,
        Cyan,
        Teal,
        Green,
        LightGreen,
        Lime,
        Yellow,
        Amber,
        Orange,
        DeepOrange,
        Brown,
        BlueGrey,
    ];

    /// <summary>The Material Design accent color swatches.</summary>
    public static readonly IReadOnlyList<MaterialAccentColor> Accents =
    [
        RedAccent,
        PinkAccent,
        PurpleAccent,
        DeepPurpleAccent,
        IndigoAccent,
        BlueAccent,
        LightBlueAccent,
        CyanAccent,
        TealAccent,
        GreenAccent,
        LightGreenAccent,
        LimeAccent,
        YellowAccent,
        AmberAccent,
        OrangeAccent,
        DeepOrangeAccent,
    ];
}
