// C#-only infrastructure: the Avalonia host's analogue of Flutter's per-embedding
// `keyboard_maps.g.dart`. Flutter generates one scan-code table per embedding (Android, GTK, Web,
// Windows, ...); Plumix has a single Avalonia host, whose `PhysicalKey` enum already uses the W3C
// `code` names that Flutter's `PhysicalKeyboardKey` constants are named after, so the physical map
// is resolved by name and only the layout-independent `Key` -> logical map is spelled out.

using Avalonia.Input;
using Plumix.UI;

namespace Plumix;

internal static class HostKeyboardMap
{
    /// <summary>
    /// The plane for keys Avalonia reports that Flutter has no constant for. Flutter reserves one
    /// plane per embedding above `LogicalKeyboardKey.StartOfPlatformPlanes` (android 0x011 through
    /// glfw 0x018); 0x019 is the next free value and is Plumix's Avalonia plane. Keys synthesized
    /// into it report `IsAutogenerated == true`, exactly like Flutter's platform-plane keys.
    /// </summary>
    internal const long AvaloniaPlane = 0x01900000000;

    /// <summary>
    /// Physical keys Avalonia knows but Flutter has no USB HID constant for are synthesized above
    /// the USB HID range so that they stay unique in `HardwareKeyboard`'s pressed-key map.
    /// </summary>
    private const long SynthesizedPhysicalBase = 0x10000000000;

    public static PhysicalKeyboardKey PhysicalKeyFor(PhysicalKey physicalKey)
    {
        string? name = Enum.GetName(physicalKey);
        if (name == null || physicalKey == PhysicalKey.None)
        {
            return new PhysicalKeyboardKey(SynthesizedPhysicalBase + (long)physicalKey);
        }

        // Avalonia spells the letter keys `A`..`Z` and the numeric pad `NumPadN`; Flutter's
        // constants are `KeyA`..`KeyZ` and `NumpadN`.
        string normalized = name.Length == 1 && char.IsAsciiLetter(name[0])
            ? $"Key{name}"
            : name.StartsWith("NumPad", StringComparison.Ordinal)
                ? string.Concat("Numpad", name.AsSpan(6))
                : name;

        return PhysicalKeyboardKey.FindKeyByGeneratedName(normalized)
               ?? new PhysicalKeyboardKey(SynthesizedPhysicalBase + (long)physicalKey);
    }

    public static LogicalKeyboardKey LogicalKeyFor(Key key, string? keySymbol)
    {
        LogicalKeyboardKey? mapped = MapLogicalKey(key);
        if (mapped != null)
        {
            return mapped;
        }

        // Keys Avalonia does not name fall back to the character the layout produced, which is how
        // Flutter's embedders resolve logical keys that are not in their scan-code table.
        if (keySymbol is { Length: > 0 })
        {
            string lowered = keySymbol.ToLowerInvariant();
            if (char.IsHighSurrogate(lowered[0]) ? lowered.Length == 2 : lowered.Length == 1)
            {
                int rune = char.ConvertToUtf32(lowered, 0);
                if (!LogicalKeyboardKey.IsControlCharacter(lowered))
                {
                    return LogicalKeyboardKey.FindKeyByKeyId(rune) ?? new LogicalKeyboardKey(rune);
                }
            }
        }

        return new LogicalKeyboardKey(AvaloniaPlane + (long)key);
    }

    public static KeyEventDeviceType DeviceTypeFor(KeyDeviceType deviceType)
    {
        return deviceType switch
        {
            KeyDeviceType.Gamepad => KeyEventDeviceType.Gamepad,
            KeyDeviceType.Remote => KeyEventDeviceType.Hdmi,
            _ => KeyEventDeviceType.Keyboard,
        };
    }

    // Aliased Avalonia members (`Enter`/`Return`, `Prior`/`PageUp`, `Oem1`/`OemSemicolon`, ...)
    // share an enum value, so only the canonical spelling appears here.
    private static LogicalKeyboardKey? MapLogicalKey(Key key)
    {
        return key switch
        {
            Key.A => LogicalKeyboardKey.KeyA,
            Key.B => LogicalKeyboardKey.KeyB,
            Key.C => LogicalKeyboardKey.KeyC,
            Key.D => LogicalKeyboardKey.KeyD,
            Key.E => LogicalKeyboardKey.KeyE,
            Key.F => LogicalKeyboardKey.KeyF,
            Key.G => LogicalKeyboardKey.KeyG,
            Key.H => LogicalKeyboardKey.KeyH,
            Key.I => LogicalKeyboardKey.KeyI,
            Key.J => LogicalKeyboardKey.KeyJ,
            Key.K => LogicalKeyboardKey.KeyK,
            Key.L => LogicalKeyboardKey.KeyL,
            Key.M => LogicalKeyboardKey.KeyM,
            Key.N => LogicalKeyboardKey.KeyN,
            Key.O => LogicalKeyboardKey.KeyO,
            Key.P => LogicalKeyboardKey.KeyP,
            Key.Q => LogicalKeyboardKey.KeyQ,
            Key.R => LogicalKeyboardKey.KeyR,
            Key.S => LogicalKeyboardKey.KeyS,
            Key.T => LogicalKeyboardKey.KeyT,
            Key.U => LogicalKeyboardKey.KeyU,
            Key.V => LogicalKeyboardKey.KeyV,
            Key.W => LogicalKeyboardKey.KeyW,
            Key.X => LogicalKeyboardKey.KeyX,
            Key.Y => LogicalKeyboardKey.KeyY,
            Key.Z => LogicalKeyboardKey.KeyZ,
            Key.D0 => LogicalKeyboardKey.Digit0,
            Key.D1 => LogicalKeyboardKey.Digit1,
            Key.D2 => LogicalKeyboardKey.Digit2,
            Key.D3 => LogicalKeyboardKey.Digit3,
            Key.D4 => LogicalKeyboardKey.Digit4,
            Key.D5 => LogicalKeyboardKey.Digit5,
            Key.D6 => LogicalKeyboardKey.Digit6,
            Key.D7 => LogicalKeyboardKey.Digit7,
            Key.D8 => LogicalKeyboardKey.Digit8,
            Key.D9 => LogicalKeyboardKey.Digit9,
            Key.NumPad0 => LogicalKeyboardKey.Numpad0,
            Key.NumPad1 => LogicalKeyboardKey.Numpad1,
            Key.NumPad2 => LogicalKeyboardKey.Numpad2,
            Key.NumPad3 => LogicalKeyboardKey.Numpad3,
            Key.NumPad4 => LogicalKeyboardKey.Numpad4,
            Key.NumPad5 => LogicalKeyboardKey.Numpad5,
            Key.NumPad6 => LogicalKeyboardKey.Numpad6,
            Key.NumPad7 => LogicalKeyboardKey.Numpad7,
            Key.NumPad8 => LogicalKeyboardKey.Numpad8,
            Key.NumPad9 => LogicalKeyboardKey.Numpad9,
            Key.Multiply => LogicalKeyboardKey.NumpadMultiply,
            Key.Add => LogicalKeyboardKey.NumpadAdd,
            Key.Subtract => LogicalKeyboardKey.NumpadSubtract,
            Key.Decimal => LogicalKeyboardKey.NumpadDecimal,
            Key.Divide => LogicalKeyboardKey.NumpadDivide,
            Key.Separator => LogicalKeyboardKey.NumpadComma,
            Key.F1 => LogicalKeyboardKey.F1,
            Key.F2 => LogicalKeyboardKey.F2,
            Key.F3 => LogicalKeyboardKey.F3,
            Key.F4 => LogicalKeyboardKey.F4,
            Key.F5 => LogicalKeyboardKey.F5,
            Key.F6 => LogicalKeyboardKey.F6,
            Key.F7 => LogicalKeyboardKey.F7,
            Key.F8 => LogicalKeyboardKey.F8,
            Key.F9 => LogicalKeyboardKey.F9,
            Key.F10 => LogicalKeyboardKey.F10,
            Key.F11 => LogicalKeyboardKey.F11,
            Key.F12 => LogicalKeyboardKey.F12,
            Key.F13 => LogicalKeyboardKey.F13,
            Key.F14 => LogicalKeyboardKey.F14,
            Key.F15 => LogicalKeyboardKey.F15,
            Key.F16 => LogicalKeyboardKey.F16,
            Key.F17 => LogicalKeyboardKey.F17,
            Key.F18 => LogicalKeyboardKey.F18,
            Key.F19 => LogicalKeyboardKey.F19,
            Key.F20 => LogicalKeyboardKey.F20,
            Key.F21 => LogicalKeyboardKey.F21,
            Key.F22 => LogicalKeyboardKey.F22,
            Key.F23 => LogicalKeyboardKey.F23,
            Key.F24 => LogicalKeyboardKey.F24,
            Key.Back => LogicalKeyboardKey.Backspace,
            Key.Tab => LogicalKeyboardKey.Tab,
            Key.Return => LogicalKeyboardKey.Enter,
            Key.Escape => LogicalKeyboardKey.Escape,
            Key.Space => LogicalKeyboardKey.Space,
            Key.PageUp => LogicalKeyboardKey.PageUp,
            Key.PageDown => LogicalKeyboardKey.PageDown,
            Key.End => LogicalKeyboardKey.End,
            Key.Home => LogicalKeyboardKey.Home,
            Key.Left => LogicalKeyboardKey.ArrowLeft,
            Key.Up => LogicalKeyboardKey.ArrowUp,
            Key.Right => LogicalKeyboardKey.ArrowRight,
            Key.Down => LogicalKeyboardKey.ArrowDown,
            Key.Insert => LogicalKeyboardKey.Insert,
            Key.Delete => LogicalKeyboardKey.Delete,
            Key.Help => LogicalKeyboardKey.Help,
            Key.Clear => LogicalKeyboardKey.Clear,
            Key.Select => LogicalKeyboardKey.Select,
            Key.Print => LogicalKeyboardKey.Print,
            Key.Execute => LogicalKeyboardKey.Execute,
            Key.Pause => LogicalKeyboardKey.Pause,
            Key.Cancel => LogicalKeyboardKey.Cancel,
            Key.Snapshot => LogicalKeyboardKey.PrintScreen,
            Key.CapsLock => LogicalKeyboardKey.CapsLock,
            Key.NumLock => LogicalKeyboardKey.NumLock,
            Key.Scroll => LogicalKeyboardKey.ScrollLock,
            Key.LeftShift => LogicalKeyboardKey.ShiftLeft,
            Key.RightShift => LogicalKeyboardKey.ShiftRight,
            Key.LeftCtrl => LogicalKeyboardKey.ControlLeft,
            Key.RightCtrl => LogicalKeyboardKey.ControlRight,
            Key.LeftAlt => LogicalKeyboardKey.AltLeft,
            Key.RightAlt => LogicalKeyboardKey.AltRight,
            Key.LWin => LogicalKeyboardKey.MetaLeft,
            Key.RWin => LogicalKeyboardKey.MetaRight,
            Key.Apps => LogicalKeyboardKey.ContextMenu,
            Key.Sleep => LogicalKeyboardKey.Sleep,
            Key.ImeConvert => LogicalKeyboardKey.Convert,
            Key.ImeNonConvert => LogicalKeyboardKey.NonConvert,
            // `HangulMode` shares Avalonia's enum value with `KanaMode`.
            Key.KanaMode => LogicalKeyboardKey.KanaMode,
            Key.BrowserBack => LogicalKeyboardKey.BrowserBack,
            Key.BrowserForward => LogicalKeyboardKey.BrowserForward,
            Key.BrowserRefresh => LogicalKeyboardKey.BrowserRefresh,
            Key.BrowserStop => LogicalKeyboardKey.BrowserStop,
            Key.BrowserSearch => LogicalKeyboardKey.BrowserSearch,
            Key.BrowserFavorites => LogicalKeyboardKey.BrowserFavorites,
            Key.BrowserHome => LogicalKeyboardKey.BrowserHome,
            Key.VolumeMute => LogicalKeyboardKey.AudioVolumeMute,
            Key.VolumeDown => LogicalKeyboardKey.AudioVolumeDown,
            Key.VolumeUp => LogicalKeyboardKey.AudioVolumeUp,
            Key.MediaNextTrack => LogicalKeyboardKey.MediaTrackNext,
            Key.MediaPreviousTrack => LogicalKeyboardKey.MediaTrackPrevious,
            Key.MediaStop => LogicalKeyboardKey.MediaStop,
            Key.MediaPlayPause => LogicalKeyboardKey.MediaPlayPause,
            Key.MediaRecord => LogicalKeyboardKey.MediaRecord,
            Key.LaunchMail => LogicalKeyboardKey.LaunchMail,
            Key.SelectMedia => LogicalKeyboardKey.LaunchMediaPlayer,
            Key.LaunchApplication1 => LogicalKeyboardKey.LaunchApplication1,
            Key.LaunchApplication2 => LogicalKeyboardKey.LaunchApplication2,
            Key.OemSemicolon => LogicalKeyboardKey.Semicolon,
            Key.OemPlus => LogicalKeyboardKey.Equal,
            Key.OemComma => LogicalKeyboardKey.Comma,
            Key.OemMinus => LogicalKeyboardKey.Minus,
            Key.OemPeriod => LogicalKeyboardKey.Period,
            Key.OemQuestion => LogicalKeyboardKey.Slash,
            Key.OemTilde => LogicalKeyboardKey.Backquote,
            Key.OemOpenBrackets => LogicalKeyboardKey.BracketLeft,
            Key.OemPipe => LogicalKeyboardKey.Backslash,
            Key.OemCloseBrackets => LogicalKeyboardKey.BracketRight,
            Key.OemQuotes => LogicalKeyboardKey.QuoteSingle,
            Key.OemBackslash => LogicalKeyboardKey.IntlBackslash,
            Key.OemClear => LogicalKeyboardKey.Clear,
            _ => null,
        };
    }
}
