using System.Diagnostics;
using Avalonia;
using Avalonia.Media;
using Plumix.Foundation;

namespace Plumix.Rendering;

// Dart parity source:
// flutter/packages/flutter/lib/src/widgets/color_filter.dart
// flutter/packages/flutter/lib/src/widgets/image_filter.dart
// flutter/packages/flutter/lib/src/rendering/proxy_box.dart (RenderShaderMask, RenderBackdropFilter)

/// <summary>Signature for a function that creates a shader for a given <see cref="Rect"/>.</summary>
/// <remarks>
/// Dart's <c>typedef ShaderCallback = Shader Function(Rect bounds)</c>. Plumix has no dart:ui
/// <c>Shader</c>; an Avalonia <see cref="IBrush"/> (what <c>Gradient.CreateShader</c> returns) stands in.
/// </remarks>
public delegate IBrush ShaderCallback(Rect bounds);

public sealed class RenderColorFilter : RenderProxyBox
{
    private ColorFilter _colorFilter;

    public RenderColorFilter(ColorFilter colorFilter, RenderBox? child = null)
    {
        _colorFilter = colorFilter ?? throw new ArgumentNullException(nameof(colorFilter));
        Child = child;
    }

    public ColorFilter ColorFilter
    {
        get => _colorFilter;
        set
        {
            ArgumentNullException.ThrowIfNull(value);
            if (_colorFilter == value)
            {
                return;
            }

            _colorFilter = value;
            MarkNeedsPaint();
        }
    }

    public override bool AlwaysNeedsCompositing => Child != null;

    public override void Paint(PaintingContext ctx, Point offset)
    {
        if (Child is null)
        {
            return;
        }

        ColorFilterLayer layer = ctx.PushColorFilter(
            offset,
            ColorFilter,
            base.Paint,
            _layer as ColorFilterLayer);
        layer.FilterBounds = new Rect(offset, Size);
        _layer = layer;
    }
}

public sealed class RenderImageFilter : RenderProxyBox
{
    private ImageFilter _imageFilter;
    private bool _enabled;

    public RenderImageFilter(
        ImageFilter imageFilter,
        bool enabled = true,
        RenderBox? child = null)
    {
        _imageFilter = imageFilter ?? throw new ArgumentNullException(nameof(imageFilter));
        _enabled = enabled;
        Child = child;
    }

    public bool Enabled
    {
        get => _enabled;
        set
        {
            if (_enabled == value)
            {
                return;
            }

            bool wasRepaintBoundary = IsRepaintBoundary;
            _enabled = value;
            if (IsRepaintBoundary != wasRepaintBoundary)
            {
                MarkNeedsCompositingBitsUpdate();
            }

            MarkNeedsPaint();
        }
    }

    public ImageFilter ImageFilter
    {
        get => _imageFilter;
        set
        {
            ArgumentNullException.ThrowIfNull(value);
            if (_imageFilter == value)
            {
                return;
            }

            _imageFilter = value;
            MarkNeedsCompositedLayerUpdate();
        }
    }

    public override bool AlwaysNeedsCompositing => Child != null && Enabled;

    public override bool IsRepaintBoundary => AlwaysNeedsCompositing;

    protected override OffsetLayer CreateCompositedLayer(OffsetLayer? oldLayer)
    {
        return oldLayer as ImageFilterLayer ?? new ImageFilterLayer();
    }

    protected override void UpdateCompositedLayer(OffsetLayer layer)
    {
        var imageFilterLayer = (ImageFilterLayer)layer;
        imageFilterLayer.ImageFilter = ImageFilter;
        imageFilterLayer.FilterBounds = new Rect(default, Size);
    }
}

/// <summary>Applies a mask generated by a shader to its child.</summary>
/// <remarks>
/// Flutter's <c>RenderShaderMask</c>. The mask is an Avalonia <see cref="IBrush"/>, Plumix's stand-in for
/// a dart:ui <c>Shader</c> (see <see cref="ShaderCallback"/>).
/// </remarks>
public class RenderShaderMask : RenderProxyBox
{
    private ShaderCallback _shaderCallback;
    private BlendMode _blendMode;

    /// <summary>Creates a render object that applies a mask generated by a shader to its child.</summary>
    public RenderShaderMask(
        ShaderCallback shaderCallback,
        RenderBox? child = null,
        BlendMode blendMode = BlendMode.Modulate) : base(child)
    {
        _shaderCallback = shaderCallback;
        _blendMode = blendMode;
    }

    /// <summary>Called to create the shader that generates the mask.</summary>
    public ShaderCallback ShaderCallback
    {
        get => _shaderCallback;
        set
        {
            if (_shaderCallback == value)
            {
                return;
            }

            _shaderCallback = value;
            MarkNeedsPaint();
        }
    }

    /// <summary>The blend mode to use when applying the shader to the child.</summary>
    public BlendMode BlendMode
    {
        get => _blendMode;
        set
        {
            if (_blendMode == value)
            {
                return;
            }

            _blendMode = value;
            MarkNeedsPaint();
        }
    }

    /// <inheritdoc />
    public override bool AlwaysNeedsCompositing => Child != null;

    /// <inheritdoc />
    public override void Paint(PaintingContext context, Point offset)
    {
        if (Child is not null)
        {
            Debug.Assert(NeedsCompositing);
            var layer = Layer as ShaderMaskLayer ?? new ShaderMaskLayer();
            Layer = layer;
            layer.Shader = _shaderCallback(new Rect(new Point(0, 0), Size));
            layer.MaskRect = new Rect(offset, Size);
            layer.BlendMode = _blendMode;
            context.PushLayer(layer, base.Paint, offset);
            if (Constants.KDebugMode)
            {
                layer.DebugCreator = DebugCreator;
            }
        }
        else
        {
            Layer = null;
        }
    }
}

/// <summary>Applies a filter to the existing painted content and then paints the child.</summary>
public class RenderBackdropFilter : RenderProxyBox
{
    private bool _enabled;
    private ImageFilterConfig _filterConfig;
    private BlendMode _blendMode;
    private BackdropKey? _backdropKey;

    /// <summary>Creates a backdrop filter.</summary>
    /// <remarks>Exactly one of <paramref name="filter"/> or <paramref name="filterConfig"/> must be provided.</remarks>
    public RenderBackdropFilter(
        RenderBox? child = null,
        ImageFilter? filter = null,
        ImageFilterConfig? filterConfig = null,
        BlendMode blendMode = BlendMode.SourceOver,
        bool enabled = true,
        BackdropKey? backdropKey = null) : base(child)
    {
        if (Constants.KDebugMode)
        {
            if (!(filter is not null || filterConfig is not null))
            {
                throw new AssertionError("Either filter or filterConfig must be provided.");
            }

            if (!(filter is null || filterConfig is null))
            {
                throw new AssertionError("Cannot provide both a filter and a filterConfig.");
            }
        }

        _filterConfig = filterConfig ?? new ImageFilterConfig(filter!);
        _enabled = enabled;
        _blendMode = blendMode;
        _backdropKey = backdropKey;
    }

    /// <summary>Whether or not the backdrop filter operation will be applied to the child.</summary>
    public bool Enabled
    {
        get => _enabled;
        set
        {
            if (Enabled == value)
            {
                return;
            }

            _enabled = value;
            MarkNeedsPaint();
        }
    }

    /// <summary>The image filter to apply to the existing painted content.</summary>
    /// <remarks>
    /// The getter should only be called when the filter is assigned via the setter; otherwise it throws an
    /// assertion error. Dart deprecates only the getter; C# cannot mark an accessor obsolete, so the whole
    /// property carries the attribute.
    /// </remarks>
    [Obsolete("Use filterConfig instead. This feature was deprecated after v3.40.0-1.0.pre.")]
    public ImageFilter Filter
    {
        get
        {
            if (Constants.KDebugMode && FilterConfig.Filter is null)
            {
                throw new AssertionError(
                    "This getter should only be called when the filter is assigned via the `filter` setter.");
            }

            return FilterConfig.Filter!;
        }
        set => FilterConfig = new ImageFilterConfig(value);
    }

    /// <summary>The configuration for the image filter to apply to the existing painted content.</summary>
    public ImageFilterConfig FilterConfig
    {
        get => _filterConfig;
        set
        {
            if (_filterConfig == value)
            {
                return;
            }

            _filterConfig = value;
            MarkNeedsPaint();
        }
    }

    /// <summary>The blend mode to use to apply the filtered background content onto the background surface.</summary>
    public BlendMode BlendMode
    {
        get => _blendMode;
        set
        {
            if (_blendMode == value)
            {
                return;
            }

            _blendMode = value;
            MarkNeedsPaint();
        }
    }

    /// <summary>The backdrop key that identifies the backdrop group this filter will read from.</summary>
    public BackdropKey? BackdropKey
    {
        get => _backdropKey;
        set
        {
            if (value == _backdropKey)
            {
                return;
            }

            _backdropKey = value;
            MarkNeedsPaint();
        }
    }

    /// <inheritdoc />
    public override bool AlwaysNeedsCompositing => Child != null;

    /// <inheritdoc />
    public override void Paint(PaintingContext context, Point offset)
    {
        if (!_enabled)
        {
            base.Paint(context, offset);
            return;
        }

        ImageFilter effectiveFilter = _filterConfig.Resolve(new ImageFilterContext(new Rect(offset, Size)));

        if (Child is not null)
        {
            Debug.Assert(NeedsCompositing);
            var layer = Layer as BackdropFilterLayer ?? new BackdropFilterLayer();
            Layer = layer;
            layer.ImageFilter = effectiveFilter;
            layer.BlendMode = _blendMode;
            layer.BackdropKey = _backdropKey;
            context.PushLayer(layer, base.Paint, offset);
            if (Constants.KDebugMode)
            {
                layer.DebugCreator = DebugCreator;
            }
        }
        else
        {
            Layer = null;
        }
    }

    /// <inheritdoc />
    public override void DebugFillProperties(DiagnosticPropertiesBuilder properties)
    {
        base.DebugFillProperties(properties);
        properties.Add(new DiagnosticsProperty<ImageFilterConfig>(
            "filterConfig",
            FilterConfig,
            defaultValue: DiagnosticsDefaults.NullValue));
        properties.Add(new EnumProperty<BlendMode>("blendMode", BlendMode));
        properties.Add(new FlagProperty("enabled", Enabled, ifTrue: "enabled"));
    }
}
