#!/usr/bin/env python3
"""Generate src/Plumix.Material/Colors.g.cs from the material_ui package's colors.dart.

`colors.dart` is 2000+ lines of pure palette data (19 primary swatches x 10 shades, 16 accent
swatches x 4 shades, grey/brown/blueGrey, and the black/white opacity constants). Transcribing it
by hand is both error-prone and expensive, so Plumix mirrors Flutter's own numbers by parsing the
Dart, the same way `scripts/generate_keyboard_keys.py` mirrors `keyboard_key.g.dart`.

Run this after moving the `material_ui` pin (see AGENTS.md).

Usage: python3 scripts/generate_material_colors.py
"""

from __future__ import annotations

import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
DART = ROOT / "material-ui-src/lib/src/colors.dart"
OUT = ROOT / "src/Plumix.Material/Colors.g.cs"

PRIVATE_VALUE_RE = re.compile(r"^  static const int (_\w+) = (0x[0-9A-Fa-f]+);$", re.MULTILINE)
PLAIN_COLOR_RE = re.compile(
    r"^  static const Color (\w+) = Color\((0x[0-9A-Fa-f]+)\);$", re.MULTILINE
)
SWATCH_RE = re.compile(
    r"static const (MaterialColor|MaterialAccentColor) (\w+) =\s*"
    r"(?:MaterialColor|MaterialAccentColor)\(\s*([^,]+),\s*<int, Color>\{(.*?)\},?\s*\);",
    re.DOTALL,
)
ENTRY_RE = re.compile(r"(\d+):\s*Color\(([^)]+)\),(?:[^\S\n]*//[^\S\n]*(.*))?")
LIST_RE = re.compile(
    r"static const List<(MaterialColor|MaterialAccentColor)> (\w+) = "
    r"<(?:MaterialColor|MaterialAccentColor)>\[(.*?)\];",
    re.DOTALL,
)

HEADER = """// Dart parity source: material_ui/lib/src/colors.dart
//
// DO NOT EDIT -- DO NOT EDIT -- DO NOT EDIT
// Generated by scripts/generate_material_colors.py from the material_ui package's colors.dart.
// Regenerate after moving the material_ui pin; edit the script, not this file.

using Avalonia.Media;

namespace Plumix.Material;

/// <summary>
/// <see cref="Color"/> and <see cref="ColorSwatch{T}"/> constants that represent Material Design's
/// color palette.
/// </summary>
public static class Colors
{
"""


def pascal(name: str) -> str:
    return name[0].upper() + name[1:]


def resolve(token: str, constants: dict[str, str]) -> str:
    token = token.strip()
    if token.startswith("0x"):
        return token.upper().replace("0X", "0x")
    if token in constants:
        return constants[token]
    raise SystemExit(f"generate_material_colors: unknown color value '{token}'")


def emit_plain(name: str, value: str) -> list[str]:
    alpha = int(value[2:4], 16)
    if name in ("transparent", "black", "white"):
        summary = f"Completely {'invisible' if name == 'transparent' else 'opaque ' + name}."
    else:
        percent = round(alpha / 255 * 100)
        base = "black" if name.startswith("black") else "white"
        summary = f"{base.capitalize()} with {percent}% opacity."
    return [
        f"    /// <summary>{summary}</summary>",
        f"    public static readonly Color {pascal(name)} = Color.FromUInt32({value});",
        "",
    ]


def emit_swatch(kind: str, name: str, primary: str, entries: list[tuple[str, str, str]]) -> list[str]:
    label = "accent swatch" if kind == "MaterialAccentColor" else "primary swatch"
    lines = [
        f"    /// <summary>The {name} {label}.</summary>",
        f"    public static readonly {kind} {pascal(name)} = new(",
        f"        {primary},",
        "        new Dictionary<int, Color>",
        "        {",
    ]
    for shade, value, comment in entries:
        suffix = f" // {comment}" if comment else ""
        lines.append(f"            [{shade}] = Color.FromUInt32({value}),{suffix}")
    lines += ["        });", ""]
    return lines


def emit_list(kind: str, name: str, members: list[str]) -> list[str]:
    summary = (
        "The Material Design accent color swatches."
        if kind == "MaterialAccentColor"
        else "The Material Design primary color swatches, excluding grey."
    )
    lines = [
        f"    /// <summary>{summary}</summary>",
        f"    public static readonly IReadOnlyList<{kind}> {pascal(name)} =",
        f"    [",
    ]
    lines += [f"        {pascal(member)}," for member in members]
    lines += ["    ];", ""]
    return lines


def main() -> int:
    if not DART.exists():
        print(f"missing {DART}; create the material-ui-src symlink (see AGENTS.md)", file=sys.stderr)
        return 1

    source = DART.read_text(encoding="utf-8")
    constants = {name: value for name, value in PRIVATE_VALUE_RE.findall(source)}

    # Order the members the way colors.dart declares them: the primaries/accents lists reference
    # the swatch fields, and C# runs static initializers in declaration order.
    members: list[tuple[int, list[str]]] = []
    for match in PLAIN_COLOR_RE.finditer(source):
        members.append((match.start(), emit_plain(match.group(1), match.group(2))))
    for match in SWATCH_RE.finditer(source):
        kind, name, primary, body = match.groups()
        entries = [
            (shade, resolve(value, constants), comment.strip())
            for shade, value, comment in ENTRY_RE.findall(body)
        ]
        # The accent swatches carry 100/200/400/700; the primaries carry 50..900, plus the two
        # extra `grey` shades (350, 850) Flutter keeps for M2 raised buttons and dark backgrounds.
        expected = {4} if kind == "MaterialAccentColor" else {10, 12}
        if len(entries) not in expected:
            raise SystemExit(f"generate_material_colors: {name} has {len(entries)} shades")
        members.append((match.start(), emit_swatch(kind, name, resolve(primary, constants), entries)))
    for match in LIST_RE.finditer(source):
        kind, name, body = match.groups()
        listed = [line.strip().rstrip(",") for line in body.splitlines()]
        listed = [line for line in listed if line and not line.startswith("//")]
        members.append((match.start(), emit_list(kind, name, listed)))

    members.sort(key=lambda item: item[0])
    lines: list[str] = []
    for _, block in members:
        lines += block
    if lines and lines[-1] == "":
        lines.pop()

    OUT.write_text(HEADER + "\n".join(lines) + "\n}\n", encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)} ({len(members)} members)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
