#!/usr/bin/env python3
"""Transpile Flutter's vitool AnimatedIcons data into Plumix C# collection expressions."""

from __future__ import annotations

import argparse
import re
from pathlib import Path


def pascal_case(value: str) -> str:
    return "".join(part.capitalize() for part in value.split("_"))


def transpile(source: str, icon_name: str) -> str:
    declaration = re.search(r"const _AnimatedIconData[\s\S]+", source)
    if declaration is None:
        raise ValueError(f"Animated icon declaration not found in {icon_name}")

    result = declaration.group(0)
    result = re.sub(
        rf"const _AnimatedIconData \_\${re.escape(icon_name)} = _AnimatedIconData\(",
        f"public static AnimatedIconData {pascal_case(icon_name)} {{ get; }} = new AnimatedIconDataImpl(",
        result,
        count=1,
    )
    replacements = (
        ("<_PathFrames>[", "["),
        ("<_PathCommand>[", "["),
        ("<double>[", "["),
        ("<Offset>[", "["),
        ("_PathFrames(", "new PathFrames("),
        ("_PathMoveTo(", "new PathMoveTo("),
        ("_PathCubicTo(", "new PathCubicTo("),
        ("_PathClose()", "new PathClose()"),
        ("Size(", "new Size("),
        ("Offset(", "new Point("),
    )
    for old, new in replacements:
        result = result.replace(old, new)
    result = re.sub(r"\],\n(\s*)\)", r"]\n\1)", result)
    return result.rstrip()


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("flutter_data", type=Path)
    parser.add_argument("output", type=Path)
    arguments = parser.parse_args()

    sources = sorted(arguments.flutter_data.glob("*.g.dart"))
    if not sources:
        raise ValueError(f"No generated AnimatedIcons data found under {arguments.flutter_data}")

    members = [transpile(path.read_text(), path.stem.removesuffix(".g")) for path in sources]
    output = """// Copyright 2014 The Flutter Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// AUTOGENERATED FILE DO NOT EDIT!
// Transpiled from Flutter's vitool output by scripts/generate_animated_icons.py.

using Avalonia;

namespace Plumix.Material;

public static partial class AnimatedIcons
{
"""
    output += "\n\n".join("    " + member.replace("\n", "\n    ") for member in members)
    output += "\n}\n"
    arguments.output.write_text(output)


if __name__ == "__main__":
    main()
