#!/usr/bin/env python3
"""Generate CupertinoIcons.g.cs and vendor the matching cupertino_icons font asset.

Flutter's icons.dart contains more than 1,300 IconData declarations. Plumix parses that pinned Dart
source instead of hand-transcribing the catalog, and copies the font/license from the exact
cupertino_icons package resolved by dart_sample.

Run this after moving the cupertino_ui or cupertino_icons pin (see AGENTS.md).

Usage: python3 scripts/generate_cupertino_icons.py
"""

from __future__ import annotations

import hashlib
import json
import pathlib
import re
import shutil
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
DART = ROOT / "cupertino-ui-src/lib/src/icons.dart"
PACKAGE_CONFIG = ROOT / "dart_sample/.dart_tool/package_config.json"
OUT = ROOT / "src/Plumix.Cupertino/CupertinoIcons.g.cs"
ASSET_DIR = ROOT / "src/Plumix.Cupertino/Assets/Fonts"

FONT_RE = re.compile(r"^  static const String iconFont = '([^']+)';$", re.MULTILINE)
PACKAGE_RE = re.compile(r"^  static const String iconFontPackage = '([^']+)';$", re.MULTILINE)
ICON_RE = re.compile(
    r"^  static const IconData (\w+)\s*=\s*IconData\(\s*"
    r"(0x[0-9a-fA-F]+)\s*,(.*?)\);$",
    re.MULTILINE | re.DOTALL,
)


def pascal(name: str) -> str:
    return "".join(part[0].upper() + part[1:] for part in name.split("_"))


def read_single(pattern: re.Pattern[str], source: str, label: str) -> str:
    match = pattern.search(source)
    if match is None:
        raise SystemExit(f"generate_cupertino_icons: could not parse {label}")
    return match.group(1)


def resolved_package_root(package_name: str) -> pathlib.Path:
    if not PACKAGE_CONFIG.exists():
        raise SystemExit(
            "generate_cupertino_icons: missing dart_sample/.dart_tool/package_config.json; "
            "run 'flutter pub get' in dart_sample"
        )

    config = json.loads(PACKAGE_CONFIG.read_text(encoding="utf-8"))
    package = next((item for item in config["packages"] if item["name"] == package_name), None)
    if package is None:
        raise SystemExit(f"generate_cupertino_icons: package '{package_name}' is not resolved")

    root_uri = package["rootUri"]
    if not root_uri.startswith("file://"):
        raise SystemExit(f"generate_cupertino_icons: unsupported package root URI '{root_uri}'")
    return pathlib.Path(root_uri.removeprefix("file://"))


def emit_icon(name: str, code_point: str, directional: bool) -> list[str]:
    arguments = f"new({code_point.lower()}, FontFamily: IconFont, FontPackage: IconFontPackage"
    if directional:
        arguments += ", MatchTextDirection: true"
    arguments += ");"
    declaration = f"    public static IconData {pascal(name)} {{ get; }} = {arguments}"
    if len(declaration) <= 120:
        return [declaration]

    lines = [f"    public static IconData {pascal(name)} {{ get; }} = new(", f"        {code_point.lower()},"]
    lines.append("        FontFamily: IconFont,")
    package_line = "        FontPackage: IconFontPackage"
    lines.append(package_line + ("," if directional else ");"))
    if directional:
        lines.append("        MatchTextDirection: true);")
    return lines


def main() -> int:
    if not DART.exists():
        print(f"missing {DART}; create the cupertino-ui-src symlink (see AGENTS.md)", file=sys.stderr)
        return 1

    source = DART.read_text(encoding="utf-8")
    font = read_single(FONT_RE, source, "iconFont")
    package = read_single(PACKAGE_RE, source, "iconFontPackage")
    icons = [
        (name, code_point.lower(), "matchTextDirection: true" in arguments)
        for name, code_point, arguments in ICON_RE.findall(source)
    ]
    if not icons:
        raise SystemExit("generate_cupertino_icons: parsed no IconData declarations")
    if len({name for name, _, _ in icons}) != len(icons):
        raise SystemExit("generate_cupertino_icons: parsed duplicate Dart member names")
    if len({pascal(name) for name, _, _ in icons}) != len(icons):
        raise SystemExit("generate_cupertino_icons: Dart names collide after C# casing conversion")

    manifest = "\n".join(
        f"{name}={code_point}:{str(directional).lower()}"
        for name, code_point, directional in icons
    )
    manifest_hash = hashlib.sha256(manifest.encode("utf-8")).hexdigest()

    out = [
        "// Dart parity source: cupertino_ui/lib/src/icons.dart",
        "//",
        "// DO NOT EDIT -- DO NOT EDIT -- DO NOT EDIT",
        "// Generated by scripts/generate_cupertino_icons.py from the cupertino_ui package's icons.dart.",
        "// Regenerate after moving the cupertino_ui or cupertino_icons pin; edit the script, not this file.",
        "",
        "using Plumix.Widgets;",
        "",
        "namespace Plumix.Cupertino;",
        "",
        "/// <summary>Identifiers for the supported Cupertino icons.</summary>",
        "public static partial class CupertinoIcons",
        "{",
        f'    public const string IconFont = "{font}";',
        "",
        f'    public const string IconFontPackage = "{package}";',
        "",
        f'    internal const string ManifestSha256 = "{manifest_hash}";',
        "",
    ]

    for index, (name, code_point, directional) in enumerate(icons):
        if index:
            out.append("")
        out.extend(emit_icon(name, code_point, directional))

    out.extend(
        [
            "",
            "    internal static IReadOnlyList<(string Name, IconData Data)> AllIcons { get; } =",
            "    [",
        ]
    )
    out.extend(f'        ("{name}", {pascal(name)}),' for name, _, _ in icons)
    out.extend(["    ];", "}"])
    OUT.write_text("\n".join(out) + "\n", encoding="utf-8")

    package_root = resolved_package_root(package)
    font_source = package_root / f"assets/{font}.ttf"
    license_source = package_root / "LICENSE"
    if not font_source.exists() or not license_source.exists():
        raise SystemExit(f"generate_cupertino_icons: incomplete font package at {package_root}")
    ASSET_DIR.mkdir(parents=True, exist_ok=True)
    shutil.copyfile(font_source, ASSET_DIR / font_source.name)
    shutil.copyfile(license_source, ASSET_DIR / "CupertinoIcons_LICENSE.txt")

    print(
        f"wrote {OUT.relative_to(ROOT)} ({len(icons)} icons, manifest {manifest_hash}); "
        f"copied {font_source.name} and license"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
