// Port of `package:intl` 0.20.3 `lib/src/plural_rules.dart` (autogenerated there from CLDR data).
// Dart keeps the operands in library-global state so the rules can stay terse; C# passes them in a
// value type instead, which is the same computation without the shared mutable state.

using System.Globalization;

namespace Plumix.Foundation.Intl;

/// <summary>The CLDR plural categories; Dart's <c>PluralCase</c>.</summary>
public enum PluralCase
{
    Zero,
    One,
    Two,
    Few,
    Many,
    Other,
}

/// <summary>Locale-specific CLDR plural rules; Dart's <c>plural_rules.dart</c>.</summary>
public static class PluralRules
{
    /// <summary>Whether plural rules specific to <paramref name="locale"/> exist.</summary>
    public static bool LocaleHasPluralRules(string locale) => Rules.ContainsKey(locale);

    /// <summary>Dart's <c>startRuleEvaluation</c> followed by invoking the locale's rule.</summary>
    public static PluralCase Select(string locale, double howMany, int? precision = 0)
    {
        Func<Operands, PluralCase> rule = Rules.TryGetValue(locale, out Func<Operands, PluralCase>? found)
            ? found
            : DefaultRule;
        return rule(new Operands(howMany, precision));
    }

    /// <summary>
    /// The CLDR plural operands of one number: <c>n</c>, <c>i</c>, <c>v</c>, <c>f</c> and <c>t</c>.
    /// </summary>
    internal readonly struct Operands
    {
        public Operands(double howMany, int? precision)
        {
            N = howMany;
            I = (int)Math.Round(howMany, MidpointRounding.AwayFromZero);
            int decimals = precision ?? Math.Min(Decimals(howMany), 3);
            V = decimals;
            double scale = Math.Pow(10, V);
            F = V == 0 ? 0 : (int)(Math.Floor(howMany * scale) % scale);
            int f = F;
            int v = V;
            while (f != 0 && f % 10 == 0)
            {
                f /= 10;
                v--;
            }

            T = f;
        }

        /// The absolute value of the number, integer and decimals.
        public double N { get; }

        /// The integer digits of <see cref="N"/>.
        public int I { get; }

        /// The number of visible fraction digits, with trailing zeros.
        public int V { get; }

        /// The visible fraction digits, with trailing zeros.
        public int F { get; }

        /// The visible fraction digits, without trailing zeros.
        public int T { get; }

        private static int Decimals(double value)
        {
            string text = value.ToString("R", CultureInfo.InvariantCulture);
            int point = text.IndexOf('.', StringComparison.Ordinal);
            return point == -1 ? 0 : text.Length - point - 1;
        }
    }

    private static double Mod(double value, double divisor)
    {
        double remainder = value % divisor;
        return remainder < 0 ? remainder + divisor : remainder;
    }

    private static int Mod(int value, int divisor)
    {
        int remainder = value % divisor;
        return remainder < 0 ? remainder + divisor : remainder;
    }

    private static bool In(double value, double first, double last) =>
        value >= first && value <= last && value == Math.Floor(value);

    private static PluralCase DefaultRule(Operands o) => PluralCase.Other;

    private static PluralCase AstRule(Operands o) =>
        o.I == 1 && o.V == 0 ? PluralCase.One : PluralCase.Other;

    private static PluralCase AfRule(Operands o) => o.N == 1 ? PluralCase.One : PluralCase.Other;

    private static PluralCase AmRule(Operands o) =>
        o.I == 0 || o.N == 1 ? PluralCase.One : PluralCase.Other;

    private static PluralCase ArRule(Operands o)
    {
        if (o.N == 0)
        {
            return PluralCase.Zero;
        }

        if (o.N == 1)
        {
            return PluralCase.One;
        }

        if (o.N == 2)
        {
            return PluralCase.Two;
        }

        if (In(Mod(o.N, 100), 3, 10))
        {
            return PluralCase.Few;
        }

        if (In(Mod(o.N, 100), 11, 99))
        {
            return PluralCase.Many;
        }

        return PluralCase.Other;
    }

    private static PluralCase BeRule(Operands o)
    {
        double mod10 = Mod(o.N, 10);
        double mod100 = Mod(o.N, 100);
        if (mod10 == 1 && mod100 != 11)
        {
            return PluralCase.One;
        }

        if (mod10 is 2 or 3 or 4 && mod100 is not (12 or 13 or 14))
        {
            return PluralCase.Few;
        }

        if (mod10 == 0 || In(mod10, 5, 9) || In(mod100, 11, 14))
        {
            return PluralCase.Many;
        }

        return PluralCase.Other;
    }

    private static PluralCase BrRule(Operands o)
    {
        double mod10 = Mod(o.N, 10);
        double mod100 = Mod(o.N, 100);
        if (mod10 == 1 && mod100 is not (11 or 71 or 91))
        {
            return PluralCase.One;
        }

        if (mod10 == 2 && mod100 is not (12 or 72 or 92))
        {
            return PluralCase.Two;
        }

        if (mod10 is 3 or 4 or 9 && !In(mod100, 10, 19) && !In(mod100, 70, 79) && !In(mod100, 90, 99))
        {
            return PluralCase.Few;
        }

        if (o.N != 0 && Mod(o.N, 1000000) == 0)
        {
            return PluralCase.Many;
        }

        return PluralCase.Other;
    }

    private static PluralCase BsRule(Operands o)
    {
        int modI10 = Mod(o.I, 10);
        int modI100 = Mod(o.I, 100);
        int modF10 = Mod(o.F, 10);
        int modF100 = Mod(o.F, 100);
        if ((o.V == 0 && modI10 == 1 && modI100 != 11) || (modF10 == 1 && modF100 != 11))
        {
            return PluralCase.One;
        }

        if ((o.V == 0 && modI10 is 2 or 3 or 4 && modI100 is not (12 or 13 or 14))
            || (modF10 is 2 or 3 or 4 && modF100 is not (12 or 13 or 14)))
        {
            return PluralCase.Few;
        }

        return PluralCase.Other;
    }

    private static PluralCase CaRule(Operands o)
    {
        if (o.I == 1 && o.V == 0)
        {
            return PluralCase.One;
        }

        if (o.I != 0 && Mod(o.I, 1000000) == 0 && o.V == 0)
        {
            return PluralCase.Many;
        }

        return PluralCase.Other;
    }

    private static PluralCase CsRule(Operands o)
    {
        if (o.I == 1 && o.V == 0)
        {
            return PluralCase.One;
        }

        if (o.I is 2 or 3 or 4 && o.V == 0)
        {
            return PluralCase.Few;
        }

        if (o.V != 0)
        {
            return PluralCase.Many;
        }

        return PluralCase.Other;
    }

    private static PluralCase CyRule(Operands o) => o.N switch
    {
        0 => PluralCase.Zero,
        1 => PluralCase.One,
        2 => PluralCase.Two,
        3 => PluralCase.Few,
        6 => PluralCase.Many,
        _ => PluralCase.Other,
    };

    private static PluralCase DaRule(Operands o) =>
        o.N == 1 || (o.T != 0 && o.I is 0 or 1) ? PluralCase.One : PluralCase.Other;

    private static PluralCase EsRule(Operands o)
    {
        if (o.N == 1)
        {
            return PluralCase.One;
        }

        if (o.I != 0 && Mod(o.I, 1000000) == 0 && o.V == 0)
        {
            return PluralCase.Many;
        }

        return PluralCase.Other;
    }

    private static PluralCase CebRule(Operands o)
    {
        int modI10 = Mod(o.I, 10);
        int modF10 = Mod(o.F, 10);
        if ((o.V == 0 && o.I is 1 or 2 or 3)
            || (o.V == 0 && modI10 is not (4 or 6 or 9))
            || (o.V != 0 && modF10 is not (4 or 6 or 9)))
        {
            return PluralCase.One;
        }

        return PluralCase.Other;
    }

    private static PluralCase FrRule(Operands o)
    {
        if (o.I is 0 or 1)
        {
            return PluralCase.One;
        }

        if (o.I != 0 && Mod(o.I, 1000000) == 0 && o.V == 0)
        {
            return PluralCase.Many;
        }

        return PluralCase.Other;
    }

    private static PluralCase GaRule(Operands o) => o.N switch
    {
        1 => PluralCase.One,
        2 => PluralCase.Two,
        >= 3 and <= 6 when o.N == Math.Floor(o.N) => PluralCase.Few,
        >= 7 and <= 10 when o.N == Math.Floor(o.N) => PluralCase.Many,
        _ => PluralCase.Other,
    };

    private static PluralCase HeRule(Operands o)
    {
        if ((o.I == 1 && o.V == 0) || (o.I == 0 && o.V != 0))
        {
            return PluralCase.One;
        }

        if (o.I == 2 && o.V == 0)
        {
            return PluralCase.Two;
        }

        return PluralCase.Other;
    }

    private static PluralCase FfRule(Operands o) => o.I is 0 or 1 ? PluralCase.One : PluralCase.Other;

    private static PluralCase IsRule(Operands o)
    {
        if ((o.T == 0 && Mod(o.I, 10) == 1 && Mod(o.I, 100) != 11)
            || (Mod(o.T, 10) == 1 && Mod(o.T, 100) != 11))
        {
            return PluralCase.One;
        }

        return PluralCase.Other;
    }

    private static PluralCase AkRule(Operands o) => o.N is 0 or 1 ? PluralCase.One : PluralCase.Other;

    private static PluralCase LtRule(Operands o)
    {
        double mod10 = Mod(o.N, 10);
        double mod100 = Mod(o.N, 100);
        if (mod10 == 1 && !In(mod100, 11, 19))
        {
            return PluralCase.One;
        }

        if (In(mod10, 2, 9) && !In(mod100, 11, 19))
        {
            return PluralCase.Few;
        }

        if (o.F != 0)
        {
            return PluralCase.Many;
        }

        return PluralCase.Other;
    }

    private static PluralCase LvRule(Operands o)
    {
        double mod10 = Mod(o.N, 10);
        double mod100 = Mod(o.N, 100);
        if (mod10 == 0 || In(mod100, 11, 19) || (o.V == 2 && In(Mod(o.F, 100), 11, 19)))
        {
            return PluralCase.Zero;
        }

        if ((mod10 == 1 && mod100 != 11)
            || (o.V == 2 && Mod(o.F, 10) == 1 && Mod(o.F, 100) != 11)
            || (o.V != 2 && Mod(o.F, 10) == 1))
        {
            return PluralCase.One;
        }

        return PluralCase.Other;
    }

    private static PluralCase MkRule(Operands o)
    {
        if ((o.V == 0 && Mod(o.I, 10) == 1 && Mod(o.I, 100) != 11)
            || (Mod(o.F, 10) == 1 && Mod(o.F, 100) != 11))
        {
            return PluralCase.One;
        }

        return PluralCase.Other;
    }

    private static PluralCase MtRule(Operands o)
    {
        if (o.N == 1)
        {
            return PluralCase.One;
        }

        if (o.N == 2)
        {
            return PluralCase.Two;
        }

        if (o.N == 0 || In(Mod(o.N, 100), 3, 10))
        {
            return PluralCase.Few;
        }

        if (In(Mod(o.N, 100), 11, 19))
        {
            return PluralCase.Many;
        }

        return PluralCase.Other;
    }

    private static PluralCase PlRule(Operands o)
    {
        int modI10 = Mod(o.I, 10);
        int modI100 = Mod(o.I, 100);
        if (o.I == 1 && o.V == 0)
        {
            return PluralCase.One;
        }

        if (o.V == 0 && modI10 is 2 or 3 or 4 && modI100 is not (12 or 13 or 14))
        {
            return PluralCase.Few;
        }

        if ((o.V == 0 && o.I != 1 && modI10 is 0 or 1)
            || (o.V == 0 && modI10 is >= 5 and <= 9)
            || (o.V == 0 && modI100 is 12 or 13 or 14))
        {
            return PluralCase.Many;
        }

        return PluralCase.Other;
    }

    private static PluralCase PtRule(Operands o)
    {
        if (o.I is 0 or 1)
        {
            return PluralCase.One;
        }

        if (o.I != 0 && Mod(o.I, 1000000) == 0 && o.V == 0)
        {
            return PluralCase.Many;
        }

        return PluralCase.Other;
    }

    private static PluralCase MoRule(Operands o)
    {
        if (o.I == 1 && o.V == 0)
        {
            return PluralCase.One;
        }

        if (o.V != 0 || o.N == 0 || (o.N != 1 && In(Mod(o.N, 100), 1, 19)))
        {
            return PluralCase.Few;
        }

        return PluralCase.Other;
    }

    private static PluralCase RuRule(Operands o)
    {
        int modI10 = Mod(o.I, 10);
        int modI100 = Mod(o.I, 100);
        if (o.V == 0 && modI10 == 1 && modI100 != 11)
        {
            return PluralCase.One;
        }

        if (o.V == 0 && modI10 is 2 or 3 or 4 && modI100 is not (12 or 13 or 14))
        {
            return PluralCase.Few;
        }

        if ((o.V == 0 && modI10 == 0)
            || (o.V == 0 && modI10 is >= 5 and <= 9)
            || (o.V == 0 && modI100 is >= 11 and <= 14))
        {
            return PluralCase.Many;
        }

        return PluralCase.Other;
    }

    private static PluralCase SiRule(Operands o) =>
        o.N is 0 or 1 || (o.I == 0 && o.F == 1) ? PluralCase.One : PluralCase.Other;

    private static PluralCase SlRule(Operands o)
    {
        int modI100 = Mod(o.I, 100);
        if (o.V == 0 && modI100 == 1)
        {
            return PluralCase.One;
        }

        if (o.V == 0 && modI100 == 2)
        {
            return PluralCase.Two;
        }

        if ((o.V == 0 && modI100 is 3 or 4) || o.V != 0)
        {
            return PluralCase.Few;
        }

        return PluralCase.Other;
    }

    private static readonly IReadOnlyDictionary<string, Func<Operands, PluralCase>> Rules =
        new Dictionary<string, Func<Operands, PluralCase>>(StringComparer.Ordinal)
        {
            ["en_ISO"] = AstRule,
            ["af"] = AfRule,
            ["am"] = AmRule,
            ["ar"] = ArRule,
            ["ar_DZ"] = ArRule,
            ["ar_EG"] = ArRule,
            ["as"] = AmRule,
            ["az"] = AfRule,
            ["be"] = BeRule,
            ["bg"] = AfRule,
            ["bm"] = DefaultRule,
            ["bn"] = AmRule,
            ["br"] = BrRule,
            ["bs"] = BsRule,
            ["ca"] = CaRule,
            ["chr"] = AfRule,
            ["cs"] = CsRule,
            ["cy"] = CyRule,
            ["da"] = DaRule,
            ["de"] = AstRule,
            ["de_AT"] = AstRule,
            ["de_CH"] = AstRule,
            ["el"] = AfRule,
            ["en"] = AstRule,
            ["en_AU"] = AstRule,
            ["en_CA"] = AstRule,
            ["en_GB"] = AstRule,
            ["en_IE"] = AstRule,
            ["en_IN"] = AstRule,
            ["en_MY"] = AstRule,
            ["en_NZ"] = AstRule,
            ["en_SG"] = AstRule,
            ["en_US"] = AstRule,
            ["en_ZA"] = AstRule,
            ["es"] = EsRule,
            ["es_419"] = EsRule,
            ["es_ES"] = EsRule,
            ["es_MX"] = EsRule,
            ["es_US"] = EsRule,
            ["et"] = AstRule,
            ["eu"] = AfRule,
            ["fa"] = AmRule,
            ["fi"] = AstRule,
            ["fil"] = CebRule,
            ["fr"] = FrRule,
            ["fr_CA"] = FrRule,
            ["fr_CH"] = FrRule,
            ["fur"] = AfRule,
            ["ga"] = GaRule,
            ["gl"] = AstRule,
            ["gsw"] = AfRule,
            ["gu"] = AmRule,
            ["haw"] = AfRule,
            ["he"] = HeRule,
            ["hi"] = AmRule,
            ["hr"] = BsRule,
            ["hu"] = AfRule,
            ["hy"] = FfRule,
            ["id"] = DefaultRule,
            ["in"] = DefaultRule,
            ["is"] = IsRule,
            ["it"] = CaRule,
            ["it_CH"] = CaRule,
            ["iw"] = HeRule,
            ["ja"] = DefaultRule,
            ["ka"] = AfRule,
            ["kk"] = AfRule,
            ["km"] = DefaultRule,
            ["kn"] = AmRule,
            ["ko"] = DefaultRule,
            ["ky"] = AfRule,
            ["ln"] = AkRule,
            ["lo"] = DefaultRule,
            ["lt"] = LtRule,
            ["lv"] = LvRule,
            ["mg"] = AkRule,
            ["mk"] = MkRule,
            ["ml"] = AfRule,
            ["mn"] = AfRule,
            ["mr"] = AfRule,
            ["ms"] = DefaultRule,
            ["mt"] = MtRule,
            ["my"] = DefaultRule,
            ["nb"] = AfRule,
            ["ne"] = AfRule,
            ["nl"] = AstRule,
            ["no"] = AfRule,
            ["no_NO"] = AfRule,
            ["nyn"] = AfRule,
            ["or"] = AfRule,
            ["pa"] = AkRule,
            ["pl"] = PlRule,
            ["ps"] = AfRule,
            ["pt"] = PtRule,
            ["pt_BR"] = PtRule,
            ["pt_PT"] = CaRule,
            ["ro"] = MoRule,
            ["ru"] = RuRule,
            ["si"] = SiRule,
            ["sk"] = CsRule,
            ["sl"] = SlRule,
            ["sq"] = AfRule,
            ["sr"] = BsRule,
            ["sr_Latn"] = BsRule,
            ["sv"] = AstRule,
            ["sw"] = AstRule,
            ["ta"] = AfRule,
            ["te"] = AfRule,
            ["th"] = DefaultRule,
            ["tl"] = CebRule,
            ["tr"] = AfRule,
            ["uk"] = RuRule,
            ["ur"] = AstRule,
            ["uz"] = AfRule,
            ["vi"] = DefaultRule,
            ["zh"] = DefaultRule,
            ["zh_CN"] = DefaultRule,
            ["zh_HK"] = DefaultRule,
            ["zh_TW"] = DefaultRule,
            ["zu"] = AmRule,
            ["default"] = DefaultRule,
        };
}
